%{?!ros_distro:%global ros_distro rolling}
%global pkg_name rc_dynamics_api
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-rolling-rc-dynamics-api
Version:        0.10.5
Release:        1%{?dist}
Summary:        ROS %{pkg_name} package

License:        BSD
URL:            http://rc-visard.com
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
The rc_dynamics_api provides an API for easy handling of the dynamic-state data
streams provided by Roboception's stereo camera with self-localization. See
http://rc-visard.com Dynamic-state estimates of the rc_visard relate to its
self-localization and ego-motion estimation. These states refer to rc_visard's
current pose, velocity, or acceleration and are published on demand via several
data streams. For a complete list and descriptions of these dynamics states and
the respective data streams please refer to rc_visard's user manual.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
The rc_dynamics_api provides an API for easy handling of the dynamic-state data
streams provided by Roboception's stereo camera with self-localization. See
http://rc-visard.com Dynamic-state estimates of the rc_visard relate to its
self-localization and ego-motion estimation. These states refer to rc_visard's
current pose, velocity, or acceleration and are published on demand via several
data streams. For a complete list and descriptions of these dynamics states and
the respective data streams please refer to rc_visard's user manual.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
The rc_dynamics_api provides an API for easy handling of the dynamic-state data
streams provided by Roboception's stereo camera with self-localization. See
http://rc-visard.com Dynamic-state estimates of the rc_visard relate to its
self-localization and ego-motion estimation. These states refer to rc_visard's
current pose, velocity, or acceleration and are published on demand via several
data streams. For a complete list and descriptions of these dynamics states and
the respective data streams please refer to rc_visard's user manual.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Tue Apr 21 2026 Felix Ruess <felix.ruess@roboception.de> - 0.10.5-1
- Autogenerated by Bloom
